spring.application.name=eurekaService-Registery
server.port=8761

# Eureka service does not need to register itself in the service registry

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Client service URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
