<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot as root parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.2</version>
        <relativePath/>
    </parent>

    <groupId>com.pratik.linkedinServices</groupId>
    <artifactId>linkedinServices</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <description>Parent POM for LinkedIn microservices</description>

    <modules>
        <module>apigatewayservice</module>
        <module>eurekaServiceRegistery</module>
        <module>chatService</module>
        <module>connectionService</module>
        <module>feedService</module>
        <module>jobsService</module>
        <module>notificationService</module>
        <module>postService</module>
        <module>recommendationService</module>
        <module>userService</module>
    </modules>

    <!-- Centralized versions -->
    <properties>
        <java.version>17</java.version>
        <lombok.version>1.18.30</lombok.version>
        <spring-cloud.version>2024.0.2</spring-cloud.version>
    </properties>

    <!-- Centralized dependency versions -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

<!--    &lt;!&ndash; Plugin management &ndash;&gt;-->
<!--    <build>-->
<!--        <pluginManagement>-->
<!--            <plugins>-->
<!--                <plugin>-->
<!--                    <groupId>org.springframework.boot</groupId>-->
<!--                    <artifactId>spring-boot-maven-plugin</artifactId>-->
<!--                    <configuration>-->
<!--                        <skip>true</skip>-->
<!--                    </configuration>-->
<!--                </plugin>-->
<!--            </plugins>-->
<!--        </pluginManagement>-->
<!--    </build>-->

</project>
